//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3_NetManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillInfo
    {
        public int idBillInfo { get; set; }
        public Nullable<int> idBill { get; set; }
        public Nullable<int> idGood { get; set; }
        public int Count { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Good Good { get; set; }
    }
}
