//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3_NetManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComputerLog
    {
        public int idLog { get; set; }
        public System.DateTime DateLogin { get; set; }
        public System.DateTime DateLogout { get; set; }
        public string idComputer { get; set; }
        public string UserName { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Computer Computer { get; set; }
    }
}
